export default [
  { title: 'Argo', year: 2012, wonBestPicture: true, genre: 'drama' },
  { title: 'The Hurt Locker', year: 2009, wonBestPicture: true, genre: 'action' },
  { title: 'The Lord of the Rings: The Return of the King', year: 2003, wonBestPicture: true, genre: 'fantasy' },
  { title: 'Gladiator', year: 2000, wonBestPicture: true, genre: 'action' },
  { title: 'The Silence of the Lambs', year: 1991, wonBestPicture: true, genre: 'drama' },
  { title: 'The Hunt for Red October', year: 1990, wonBestPicture: false, genre: 'action' },
  { title: 'Seven Years in Tibet', year: 1997, wonBestPicture: false, genre: 'drama' },
  { title: 'Frost/Nixon', year: 2008, wonBestPicture: false, genre: 'drama' },
  { title: 'Ghost Writer', year: 2010, wonBestPicture: false, genre: 'drama' },
  { title: 'Inside Out', year: 2014, wonBestPicture: false, genre: 'drama' },
  { title: 'Deadpool', year: 2015, wonBestPicture: false, genre: 'action' },
  { title: 'The Incredibles', year: 2004, wonBestPicture: false, genre: 'action' },
  { title: 'Iron Man', year: 2008, wonBestPicture: false, genre: 'action' },
  { title: 'Equilibrium', year: 2002, wonBestPicture: false, genre: 'action' },
  { title: 'Looper', year: 2012, wonBestPicture: false, genre: 'action' },
  { title: 'I, Robot', year: 2004, wonBestPicture: false, genre: 'action' },
  { title: 'Crouching Tiger, Hidden Dragon', year: 2000, wonBestPicture: false, genre: 'action' },
  { title: 'Willow', year: 1988, wonBestPicture: false, genre: 'fantasy' },
  { title: 'Princess Bride', year: 1987, wonBestPicture: false, genre: 'fantasy' },
  { title: 'Harry Potter and the Goblet of Fire', year: 2005, wonBestPicture: false, genre: 'fantasy' },
  { title: 'Interstellar', year: 2014, wonBestPicture: false, genre: 'sci-fi' },
  { title: 'Star Wars VII: The Force Awakens', year: 2015, wonBestPicture: false, genre: 'sci-fi' },
  { title: 'Moon', year: 2009, wonBestPicture: false, genre: 'sci-fi' },
  { title: '2001: A Space Odyssey', year: 1968, wonBestPicture: false, genre: 'sci-fi' },
  { title: 'Hannibal', year: 2001, wonBestPicture: false, genre: 'suspense' },
  { title: 'The Game', year: 1997, wonBestPicture: false, genre: 'suspense' },
  { title: 'The Spanish Prisoner', year: 1997, wonBestPicture: false, genre: 'suspense' },
  { title: 'The Manchurian Candidate', year: 1962, wonBestPicture: false, genre: 'suspense' },
];
